# Generated by Django 3.2.4 on 2021-06-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Фото', models.ImageField(upload_to='')),
                ('Дата поста', models.DateTimeField()),
                ('Описание к посту', models.TextField(max_length=500)),
                ('Никнэйм юзера', models.CharField(max_length=50)),
                ('Аватар профиля', models.ImageField(upload_to='')),
                ('Местоположение', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
