# Generated by Django 3.2.4 on 2021-06-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='Дата поста',
        ),
        migrations.AddField(
            model_name='posts',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
