# Generated by Django 3.2.4 on 2021-06-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210609_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='Аватар профиля',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='Фото',
        ),
    ]
