# Generated by Django 3.2.4 on 2021-06-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_posts_наименование поста'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='Наименование поста',
            new_name='title',
        ),
    ]
