# Generated by Django 3.2.4 on 2021-06-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_наименование поста_posts_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='Местоположение',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='Никнэйм юзера',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='Описание к посту',
        ),
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.TextField(default='description', max_length=500, verbose_name='Описание к посту'),
        ),
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(default='', upload_to='posts_media/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='posts',
            name='place',
            field=models.CharField(default='place', max_length=50, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='posts',
            name='user_avatar',
            field=models.ImageField(default='', upload_to='posts_media/', verbose_name='Аватар профиля'),
        ),
        migrations.AddField(
            model_name='posts',
            name='user_nickname',
            field=models.CharField(default='user_nickname', max_length=50, verbose_name='Никнэйм юзера'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(default='title', max_length=50),
        ),
    ]
