# Generated by Django 3.2.4 on 2021-06-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210610_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='datetime',
            field=models.DateTimeField(default='null'),
        ),
    ]
